1. What is a Python library? Why ^o we use Python libraries?

A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. Other than pre-compiled codes, a library may contain documentation, configuration data, message templates, classes, and values, etc.
We use libraries so that we don’t need to write the code again in our program that is already available. 

2. What is the difference between Numpy array and List?

Numpy arrays is a typed array, the array in memory stores a homogenous, densely packed numbers.

Python list is a heterogeneous list, the list in memory stores references to objects rather than the number themselves.

In [10]:
import numpy as np

In [13]:
#3. Find the shape, size and dimension of the following array?
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
len(a)

3

In [15]:
a.ndim

2

In [16]:
a.size

12

In [17]:
a.shape

(3, 4)

In [21]:
#4. Write python co^e to access the first row of the following array?
b= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
b[0]

array([1, 2, 3, 4])

In [25]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
c=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
c[2,3]

12

In [29]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
d=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
d[1,1],[1,3]

(6, [1, 3])

In [36]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [49]:
e=np.random.randint(0,1, size=(3,3))
e

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
#8. Describe the difference between np.random.rand and np.random.randn?

In [52]:
f=np.random.randn(1,3)
f

array([[ 0.08191732,  1.56939247, -1.14102681]])

Numpy random randn creates new Numpy arrays, but the numbers returned have a very specific structure: Numpy random randn returns numbers that are generated randomly from the normal distribution.

In [53]:
g=np.random.rand(1,3)
g

array([[0.1596067 , 0.19920386, 0.18829303]])

np.random.rand() generates random numbers from the standard uniform distribution (i.e., the uniform distribution from 0 to 1), and outputs those numbers as a Numpy array.

In [54]:
#9. Write co^e to increase the dimension of the following array?
h=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
i=np.expand_dims(h, axis =1)
i

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [57]:
#10. How to transpose the following array in NumPy?
j=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
j.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [63]:
#11. Consider the following matrix:
Matrix_A2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [67]:
Matrix_A2.shape

(3, 4)

In [69]:
Matrix_B2.shape

(3, 4)

In [70]:
Matrix_B3=np.array([[1, 2, 3],[5, 6, 7],[9, 10, 11],[12,13,14]])

In [71]:
Matrix_B3.shape

(4, 3)

In [64]:
#Index wise multiplication
Matrix_A2*Matrix_B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [72]:
 #Matix multiplication
Matrix_A2@Matrix_B3

array([[ 86,  96, 106],
       [194, 220, 246],
       [302, 344, 386]])

In [73]:
# Add both the maticK
Matrix_A2 + Matrix_B2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [78]:
# Subtact matix B from A
Matrix_B2 - Matrix_A2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
#Divide Matix B by A
Matrix_B2 / Matrix_A2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
#12. Which function in Numpy can be used to swap the byte order of an array?
a.byteswap ()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

# 13. What is the significance of the np.linalg.inv function?
The NumPy linalg.inv function which can be used to determine the multiplicative inverse of a matrix of order n. The multiplicative inverse of a matrix is the reciprocal of a regular matrix just like the reciprocal of any other number in arithmetic.

# 14. What does the np.reshape function do, and how is it used?
The numpy.reshape() function is useful when we need to change the dimensions of an array, for example, when we want to convert a one-dimensional array into a two-dimensional array or vice versa. It can also be used to create arrays with a specific shape, such as matrices and tensors.

# 15. What is broadcasting in Numpy?
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 